version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest
    hostname: mysql
    container_name: mysql
    ports:
     - 23306:3306
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
